language: python

branches:
  only:
    - master

sudo: true

matrix:
  include:
    - python: 3.6

install:
  - pip install -U pip setuptools wheel tox-travis
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y - ppa:mc3man/trusty-media ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y - ffmpeg ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ffmpeg cairo ; fi

script:
  - tox

