language: python

branches:
  only:
    - master

sudo: true

matrix:
  include:
    - python: 3.6

install:
  - pip install -U pip setuptools wheel tox-travis
  - sudo apt-get install -y - ffmpeg
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ffmpeg cairo ; fi

script:
  - tox

