# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.12' ]
        os: [ ubuntu-latest, macos-13, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - uses: conda-incubator/setup-miniconda@v3
      with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: bash -el {0}
      run: |
        conda install ffmpeg=6.1.1 pytest
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest pytest-cov
        pip install -r requirements.txt
    - name: Lint with flake8
      shell: bash -el {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      shell: bash -el {0}
      run: |
        pytest --cov=birdwatcher --cov-report=xml --cov-config=.coveragerc
    - uses: codecov/codecov-action@v5
      with:
        verbose: true # optional (default = false)